title: Rushil Singh
description: Personal Website - Rushil Singh - Software Engineer
logo: /assets/img/logo.png
introduction: Rushil Singh is a quality-oriented software engineering professional, with over 4 years of experience and proven knowledge of software development, working in the video technology domain with a focus on information security, intelligence gathering and data engineering.
show_downloads: true
resume_url: Resume_RushilSingh.pdf 
google_analytics:
theme: jekyll-theme-minimal
github:
  owner_name: Rushil Singh
  owner_url: https://github.com/rushilsingh
  repository_url: https://github.com/rushilsingh/rushilsingh.github.io
docs:
- title: About
  url: index.html

- title: Projects
  url: projects.html
