title: Rushil Singh
description: Personal Website - Rushil Singh - Software Engineer
logo: /assets/img/logo.png
introduction: Rushil Singh is a software engineer working in the video technology domain in the fields of information security, intelligence gathering and data engineering.
show_downloads: true
resume_url: Resume_RushilSingh.pdf 
google_analytics:
theme: jekyll-theme-minimal
github:
  owner_name: Rushil Singh
  owner_url: https://github.com/rushilsingh
  repository_url: https://github.com/rushilsingh/rushilsingh.github.io
docs:
- title: About
  url: index.html

- title: Projects
  url: projects.html
